/**
 * `owlwarden init --agent-rules` — write a short rules file agents can load.
 *
 * Derived from the compiled-in catalogue so it cannot drift from what `scan`
 * actually checks. Idempotent: overwrites the previous generated file when the
 * marker comment is present.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { ruleMetaListSchema, type RuleMeta } from "@dointhai/owlwarden-sdk";

import type { NativeEngine } from "../native.js";
import { EXIT } from "../exit.js";

const MARKER = "<!-- owlwarden:agent-rules -->";
const DEFAULT_OUT = ".owlwarden/agent-rules.md";

export interface InitOptions {
  /** Write the agent-rules file. */
  agentRules: boolean;
  /** Output path; default `.owlwarden/agent-rules.md`. */
  out?: string;
}

/** Runs `owlwarden init`. */
export async function runInit(
  native: NativeEngine,
  options: InitOptions,
  cwd: string,
  stderr: NodeJS.WritableStream,
): Promise<number> {
  if (!options.agentRules) {
    stderr.write("error: init currently supports --agent-rules only\n");
    return EXIT.ERROR;
  }

  const rules = ruleMetaListSchema.parse(JSON.parse(native.listRules()));
  const outPath = resolve(cwd, options.out ?? DEFAULT_OUT);
  const body = renderAgentRules(rules);

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, body, "utf8");
  stderr.write(`wrote ${outPath}\n`);
  return EXIT.CLEAN;
}

function renderAgentRules(rules: RuleMeta[]): string {
  const lines: string[] = [
    MARKER,
    "",
    "# Security conventions (generated by owlwarden)",
    "",
    "Generated from the rules compiled into this owlwarden build. Re-run",
    "`owlwarden init --agent-rules` after upgrading the tool.",
    "",
    "Do not suppress findings without a human-owned reason. Prefer fixing.",
    "",
    "## How to re-check",
    "",
    "```bash",
    "npx owlwarden scan --format json",
    "npx owlwarden explain <rule-id>",
    "```",
    "",
    "## Rules",
    "",
  ];

  for (const rule of rules) {
    lines.push(`### \`${rule.id}\``);
    lines.push("");
    lines.push(`**${rule.title}** (${rule.severity})`);
    lines.push("");
    lines.push(rule.description.trim());
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}
