//! Parsing a single file with oxc, and handing the AST to a closure.
//!
//! The AST lives in an arena that is dropped when this function returns, which
//! is why the API is "call me back" rather than "here is your AST". That is
//! also the reason [`SourceProvider::ast`](owlwarden_core::SourceProvider) does
//! not exist — see the note in `owlwarden_core::source`.

use std::path::Path;

use owlwarden_core::detector::DetectorError;
use owlwarden_core::source::RelPath;
use oxc_allocator::Allocator;
use oxc_parser::{ParseOptions, Parser};
use oxc_span::SourceType;

use crate::line_index::LineIndex;
use crate::unit::{FileUnit, UnitMeta};

/// A file that could not be parsed.
#[derive(Debug, Clone, thiserror::Error)]
#[error("{path}: {message}")]
pub struct ParseFailure {
    /// Project-relative path.
    pub path: String,
    /// First parser diagnostic, or a description of the fatal failure.
    pub message: String,
}

impl From<ParseFailure> for DetectorError {
    fn from(failure: ParseFailure) -> Self {
        Self::Parse {
            path: failure.path,
            message: failure.message,
        }
    }
}

/// Bracket nesting a file may contain before we refuse to parse it.
///
/// oxc's parser is recursive and has no depth limit of its own: around 2–4k
/// levels of nesting it overflows the stack and aborts the *process*. A scanner
/// that a source file can crash is a denial of service in a tool whose whole
/// job is reading untrusted-ish code, so we check first and skip the file.
///
/// 256 is far above anything hand-written or generated by a bundler; measured
/// TypeScript in the wild does not exceed ~40.
const MAX_NESTING_DEPTH: u32 = 256;

/// Cheap upper bound on how deeply the file nests.
///
/// Counts brackets without lexing, so it does not know that a bracket inside a
/// string literal is not real nesting. That makes it *over*-estimate on
/// pathological string content, which costs us a skipped file — the safe
/// direction. It can under-estimate only if a file contains hundreds of
/// unbalanced closing brackets inside strings, and even then oxc tolerates an
/// order of magnitude more depth than this limit allows.
fn exceeds_nesting_limit(source: &str) -> bool {
    let mut depth: u32 = 0;
    for byte in source.bytes() {
        match byte {
            b'(' | b'[' | b'{' => {
                depth = depth.saturating_add(1);
                if depth > MAX_NESTING_DEPTH {
                    return true;
                }
            }
            b')' | b']' | b'}' => depth = depth.saturating_sub(1),
            _ => {}
        }
    }
    false
}

/// Parses `source` and runs `f` against the resulting AST.
///
/// A file with syntax errors is **not** analysed. Rules reason about shapes in
/// the tree, and oxc's error recovery produces a tree that is plausible rather
/// than true — running rules over it invents findings that are not in the
/// user's code. The user's own compiler will report the syntax error; we say
/// nothing about the file and record that we skipped it.
///
/// # Errors
/// [`ParseFailure`] when the file does not parse cleanly.
pub fn with_parsed<T>(
    path: &RelPath,
    source: &str,
    meta: UnitMeta,
    f: impl FnOnce(&FileUnit<'_>) -> T,
) -> Result<T, ParseFailure> {
    if exceeds_nesting_limit(source) {
        return Err(ParseFailure {
            path: path.to_string(),
            message: format!("nesting exceeds the {MAX_NESTING_DEPTH}-level parser limit"),
        });
    }

    let source_type = SourceType::from_path(Path::new(path.as_str())).unwrap_or_else(|_| {
        // Only reachable for an extension the engine should have filtered out
        // already; TSX is the most permissive superset, so it recovers the most.
        SourceType::tsx()
    });

    let allocator = Allocator::default();
    let parsed = Parser::new(&allocator, source, source_type)
        .with_options(ParseOptions {
            // We never inspect regex internals, and parsing them is a
            // measurable slice of total parse time.
            parse_regular_expression: false,
            ..ParseOptions::default()
        })
        .parse();

    if parsed.panicked {
        return Err(ParseFailure {
            path: path.to_string(),
            message: "parser could not recover".to_owned(),
        });
    }
    if let Some(first) = parsed.diagnostics.first() {
        return Err(ParseFailure {
            path: path.to_string(),
            message: first.to_string(),
        });
    }

    let unit = FileUnit {
        path,
        source,
        program: &parsed.program,
        line_index: LineIndex::new(source),
        meta,
    };
    Ok(f(&unit))
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    fn rel(path: &str) -> RelPath {
        RelPath::new(Path::new(path)).unwrap()
    }

    fn meta() -> UnitMeta {
        UnitMeta::generic()
    }

    #[test]
    fn parses_typescript_with_types_and_decorators() {
        let path = rel("src/users.controller.ts");
        let source = r"
@Controller('users')
export class UsersController {
  @Get()
  findAll(): Promise<User[]> { return this.service.findAll() }
}
";
        let body_count =
            with_parsed(&path, source, meta(), |unit| unit.program.body.len()).unwrap();
        assert_eq!(body_count, 1);
    }

    #[test]
    fn parses_tsx() {
        let path = rel("app/page.tsx");
        let source = "export default function Page() { return <div>hi</div> }";
        assert!(with_parsed(&path, source, meta(), |_| ()).is_ok());
    }

    #[test]
    fn a_file_with_syntax_errors_is_refused_rather_than_guessed() {
        let path = rel("broken.ts");
        let failure = with_parsed(&path, "export function ( { {", meta(), |_| ()).unwrap_err();
        assert_eq!(failure.path, "broken.ts");
        assert!(!failure.message.is_empty());
    }

    #[test]
    fn deeply_nested_input_is_refused_before_it_can_overflow_the_stack() {
        // Without the guard this aborts the whole process, tests included.
        let path = rel("nested.ts");
        let source = format!("const a = {}1{};", "(".repeat(20_000), ")".repeat(20_000));
        let failure = with_parsed(&path, &source, meta(), |_| ()).unwrap_err();
        assert!(
            failure.message.contains("nesting"),
            "expected the depth guard, got: {}",
            failure.message
        );
    }

    #[test]
    fn ordinary_nesting_is_not_refused() {
        // Deeply-chained but realistic code must still be analysed.
        let path = rel("nested.ts");
        let source = format!("const a = {}1{};", "(".repeat(64), ")".repeat(64));
        assert!(with_parsed(&path, &source, meta(), |_| ()).is_ok());
    }

    #[test]
    fn empty_file_parses_to_an_empty_program() {
        let path = rel("empty.ts");
        let count = with_parsed(&path, "", meta(), |unit| unit.program.body.len()).unwrap();
        assert_eq!(count, 0);
    }
}
